pipeline {
  agent none
  environment {
    ENABLE_API_SANITY = true
    SANITY_TEST_DURATION_MINS = 2
    MAX_VUS_CHECKOUT = 50
    EUX_THREADS = 2
    ENABLE_FULL_WEB = true
    E2E_TEST_DURATION_MINS = 5
  }
  stages {
    stage('Grab Infra Repo') {
      agent { label 'master' }
      steps {
        git(branch: "$NL_VERSION", url: 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/infrastructure', credentialsId: 'CodeCommit')
      }
    }
    stage('Prep Env Config') {
      agent { label 'master' }
      steps {
        script {
          nlwToken = ""
          try { nlwToken = "$NLW_TOKEN" } catch(Exception e) { }
          if(!nlwToken?.trim())
            nlwToken = 'a8e8f0c5a4f90c02bfddcb6881e7f6811da26864879a7bd6' // defaults to Thomas
          env.NLW_TOKEN = nlwToken
          env.APM_DASHBOARD = "https://vwv51099.live.dynatrace.com/#dashboard;id=b832b009-8a4d-45fa-8488-33214bf07443;gtf=l_30_MINUTES"
        }
      }
    }
    stage('Define Dynamic Scenario') {
      agent { label 'master' }
      steps {
        script {
          if(env.ENABLE_FULL_WEB.toBoolean()) { // create a dynamic full scenario
            writeFile file: "yaml/scenarios/eux-and-apm.yaml", text: """
scenarios:
- name: dynMixedScenarioEUXwAPM
  populations:
  - name: popPost
    rampup_load:
      duration: ${env.E2E_TEST_DURATION_MINS}m
      min_users: 1
      max_users: 15
      increment_users: 1
      increment_every: 15s
  - name: dynatracePop
    constant_load:
      duration: ${env.E2E_TEST_DURATION_MINS}m
      users: 1
  - name: popSelenium
    rampup_load:
      duration: ${env.E2E_TEST_DURATION_MINS}m
      min_users: 1
      max_users: ${env.EUX_THREADS}
      increment_users: 1
      increment_every: 20s
  - name: popCloudWatch
    constant_load:
      duration: ${env.E2E_TEST_DURATION_MINS}m
      users: 1
          """
            stash includes: 'yaml/scenarios/eux-and-apm.yaml', name: 'yaml-e2e'
          }
        }
      }
    }
    stage('Start NeoLoad infrastructure') { // load generators
      agent { label 'master' }
      steps {
        sh 'docker-compose -f neoload/lg/docker-compose.yml up -d'
        sh "mkdir -p $WORKSPACE/logs"
        stash includes: 'neoload/lg/lg.yaml', name: 'yaml-LG'
        stash includes: 'neoload/lg/local-lg.txt', name: 'local-LG'
        stash includes: 'neoload/lg/docker-lg.txt', name: 'docker-LG'
      }
    }
    stage('Load Tests') {
      agent {
        dockerfile { // load controller
          args "--user root -v /tmp:/tmp --network cpv -p 7400:7400 -v /var/lib/jenkins/workspace/NL-test/logs:/root/.neotys/neoload/v6.10/logs:rw,z"
          dir 'neoload/controller'
        }
      }
      stages {
        stage('Git Project') { // a custom project with Selenium integrated
          steps {
            dir('neoload_68') {
              git(branch: "$NL_VERSION", url: 'https://github.com/paulsbruce/neoload_68.git')
            }
          }
        }
        stage('Sanity Check') {
          steps {
            script {
              if(env.ENABLE_API_SANITY.toBoolean()) {
                unstash 'docker-LG'

                  neoloadRun executable: '/home/neoload/neoload/bin/NeoLoadCmd',
                    project: "$WORKSPACE/neoload_68/demo.nlp",
                    scenario: "dynAPISanityCheck", // this is a YAML file in the yaml/scenarios directory
                    testName: "API Sanity Check (build ${BUILD_NUMBER})",
                    testDescription: "A short, small API load test",
                    autoArchive: 'true', // (default=true) if sanity fails, retain these results
                    sharedLicense: [
                        server: 'NeoLoad Demo License',
                        duration: 1,
                        vuCount: env.MAX_VUS_CHECKOUT
                    ],
                    commandLineOption: "-nlweb -nlwebToken ${env.NLW_TOKEN} -variables"+
                                       " app_server_hostname=10.0.0.10"+ // dynamic target stack
                                       " -project $WORKSPACE/neoload_68/yaml/demo.yaml"+ // static file from repo
                                       " -project $WORKSPACE/neoload_68/yaml/scenarios/dynAPISanityCheck.yaml"+ // dynamic file from above
                                       " -L API_just_ushahidi=$WORKSPACE/neoload/lg/docker-lg.txt"+ // dynamic from above
                                       " -L dynatracePop=$WORKSPACE/neoload/lg/local-lg.txt"+ // dynamic from above
                                       " -L popCAdvisor=$WORKSPACE/neoload/lg/local-lg.txt"+ // dynamic from above
                                       ""
              } else {
                echo "Sanity check skipped by configuration"
              }
            }
          }
          post {
            failure {
              archiveArtifacts "/root/.neotys/neoload/v$NL_VERSION/logs/**"
            }
          }
        }
        stage('Full E2E') {
          parallel {
            stage('Load with APM and EUX') {
                steps {
                    script { // plugin for scripted pipeline, fit to declarative syntax
                      if(env.ENABLE_FULL_WEB.toBoolean()) {
                        unstash 'local-LG'
                        unstash 'docker-LG'
                        unstash 'yaml-e2e'
                        try { // archive results regardless of overall success/fail (could be due to SLAs)

                          neoloadRun executable: '/home/neoload/neoload/bin/NeoLoadCmd',
                              project: "${env.WORKSPACE}/neoload_68/demo.nlp",
                              scenario: "dynMixedScenarioEUXwAPM",
                              testName: "Load Test w/ APM (build ${BUILD_NUMBER})",
                              testDescription: "Based on demo-mixed.yaml",
                              trendGraphs: ['AvgResponseTime', 'ErrorRate'],
                              sharedLicense: [
                                  server: 'NeoLoad Demo License',
                                  duration: 1,
                                  vuCount: env.MAX_VUS_CHECKOUT
                              ],
                              commandLineOption: "-nlweb -nlwebToken ${env.NLW_TOKEN} -variables"+ // variables below must be executed all as one line
                                                 " app_server_hostname=10.0.0.10"+ // dynamic target stack
                                                 ",ControllerAPIHostAndPort=10.0.0.10:7400"+
                                                 ",TargetHostBaseUrl=http://10.0.0.10"+
                                                 ",SeleniumHubHostAndPort=10.0.0.15:4444"+
                                                 ",JRE_JAVA=/home/neoload/neoload/jre/bin/java"+
                                                 " -project $WORKSPACE/neoload_68/yaml/demo.yaml"+ // static file from repo
                                                 " -project $WORKSPACE/yaml/scenarios/eux-and-apm.yaml"+ // dynamic file from above
                                                 " --override-lg popPost=$WORKSPACE/neoload/lg/docker-lg.txt"+ // dynamic from above
                                                 " -L dynatracePop=$WORKSPACE/neoload/lg/local-lg.txt"+ // dynamic from above
                                                 " -L popSelenium=$WORKSPACE/neoload/lg/local-lg.txt"+ // dynamic from above
                                                 " -L popCloudWatch=$WORKSPACE/neoload/lg/local-lg.txt"+ // dynamic from above
                                                 ""

                        } catch(Exception e) {
                          //sh "sleep 30s" // wait for reports to sync from node to master (Jenkins workaround)
                          // archive the dynamic stuff we did
                          archiveArtifacts "$WORKSPACE/yaml/eux-and-apm.yaml"
                          // archive the usual suspects
                          archiveArtifacts "logs/**"
                          archiveArtifacts "neoload-report/**"
                          junit allowEmptyResults: true, testResults: "neoload-report/junit*.xml"
                          // pass along the goodness
                          throw e
                        }
                      } else {
                        echo "E2E test skipped by configuration"
                      }
                    }
                }
            }
            stage('While Test Running') {
              steps {
                script {
                  if(env.ENABLE_FULL_WEB.toBoolean()) {
                    // make it easy to get to APM view of things (delay ~3min)
                    sh """
                    echo
                    echo --- APM Dashboard ---
                    echo "$env.APM_DASHBOARD"
                    echo ---
                    """
                  }
                }
                /*
                script { // example of using controller API to check/stop test
                  try { // catch timeout (i.e. if we explicitly want to ensure pipeline duration max)
                    def beyond_timeout = 2//env.E2E_TEST_DURATION_MINS.toInteger() - 5; // fake this to proof handling
                    echo "beyond_timeout: "+beyond_timeout
                    sh "sleep 40s"
                    timeout(time: beyond_timeout, unit:'MINUTES') {
                      sh "sleep 20s"
                      sh "RESPONSE=\"...TEST_RUNNING...\"; while [ grep -q TEST_RUNNING <<<\"\$RESPONSE\" ]; do echo -n '.'; sleep 10s; RESPONSE=\$(wget --post-data='{\"d\":{}}' --header='Content-Type: application/json' -s http://10.0.0.10:7400/Runtime/v1/Service.svc/GetStatus); done"
                    } // timeout
                  } catch(Exception e) {
                    echo 'Timeout!!!'
                    echo e.toString()
                    try {
                      sh "curl -d '{\"d\":{\"ForceStop\":true}}' -H 'Content-Type: application/json' -s -X POST http://10.0.0.10:7400/Runtime/v1/Service.svc/StopTest"
                    } catch(Exception e1) {
                      echo 'Timeout critical fail!!!'
                      echo e1.toString()
                    }
                    throw e
                  }
                }
                */
              }
            }
          }
        }
      }
      post {
        failure {
          archiveArtifacts "/root/.neotys/neoload/v$NL_VERSION/logs/**"
        }
      }
    }
    stage('After Test Exits') {
        steps {
          echo "Test exited without any process errors."
        }
    }
  }
  post {
      always {
        node('master') {
          sh 'docker-compose -f neoload/lg/docker-compose.yml down'
        }
      }
  }
}
